### ISSUE TITLE
FromText and ToText are not in scope.

### ISSUE THREAD

**Issue by wpoosanguansit** [k-bx/owlcloud#3]
Hi,

I tried to follow your tutorial and I keep getting error on FromText and ToText not in scope.  I have imported all of the libs found in your cabal but I still can't seem to resolve the issue.  Is there anything else that need to be setup?  Thanks for your help.

**Comment by k-bx** [comment]
@wpoosanguansit they were renamed in latest servant release, will check out if I can update the code for that. Meanwhile – feel free to try the servant < 0.6. Thanks for spotting.

**Comment by k-bx** [comment]
All right, fixed now. @wpoosanguansit some bugs might be still left in the post itself with regards to older code, since it's quite hard to check with compiler unfortunately, so PRs with fixes are welcome. Code works fine.

**Comment by wpoosanguansit** [comment]
Thank!  A quick on the doc, 

newtype SigninToken = SigninToken Text
    deriving (ToJSON, FromJSON, FromHttpApiData, ToHttpApiData, Ord, Eq)

was not updated yet.  It is still 

newtype SigninToken = SigninToken Text
    deriving (ToJSON, FromJSON, FromText, ToText, Ord, Eq)

**Comment by k-bx** [comment]
Fixed, thanks
